In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\atewa\Downloads\titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df1 = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin','Parch','SibSp','Embarked'], axis=1)

In [8]:
df1

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [9]:
df1.dropna(inplace=True)

In [15]:
df1

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
885         0       3  female  39.0  29.1250
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[714 rows x 5 columns]

In [1]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()

KeyboardInterrupt:

In [17]:
df1['sex_n']=le_sex.fit_transform(df1['Sex'])

In [ ]:
df1

     Survived  Pclass     Sex   Age     Fare  sex_n
0           0       3    male  22.0   7.2500      1
1           1       1  female  38.0  71.2833      0
2           1       3  female  26.0   7.9250      0
3           1       1  female  35.0  53.1000      0
4           0       3    male  35.0   8.0500      1
..        ...     ...     ...   ...      ...    ...
885         0       3  female  39.0  29.1250      0
886         0       2    male  27.0  13.0000      1
887         1       1  female  19.0  30.0000      0
889         1       1    male  26.0  30.0000      1
890         0       3    male  32.0   7.7500      1

[714 rows x 6 columns]

In [19]:
df1.drop(['Sex'], axis=1, inplace=True)
df1

     Survived  Pclass   Age     Fare  sex_n
0           0       3  22.0   7.2500      1
1           1       1  38.0  71.2833      0
2           1       3  26.0   7.9250      0
3           1       1  35.0  53.1000      0
4           0       3  35.0   8.0500      1
..        ...     ...   ...      ...    ...
885         0       3  39.0  29.1250      0
886         0       2  27.0  13.0000      1
887         1       1  19.0  30.0000      0
889         1       1  26.0  30.0000      1
890         0       3  32.0   7.7500      1

[714 rows x 5 columns]

In [20]:
input = df1.drop('Survived', axis=1)
output = df1['Survived']

In [21]:
from sklearn import tree
md = tree.DecisionTreeClassifier()
md.fit(input, output)

DecisionTreeClassifier()

In [22]:
md.score(input, output)

0.9845938375350141

In [23]:
md.predict([[3,22,40,1]])

c:\Users\atewa\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [24]:
md.predict([[1, 23, 70, 1]])

c:\Users\atewa\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])